#!/bin/bash
#
# fvmd        Startup script for log server.
#
# chkconfig: 345 90 4

# Source function library.
. /etc/init.d/functions

export LD_LIBRARY_PATH=/usr/local/lib
RETVAL=0
SRV_HOME=RV_SRVD_HOME
usr_n=RV_SRVD_USR
exe_n=fvm
srv_n="$exe_n"d
if [ "$usr_n" == "" ];then
    usr_n=$srv_n
fi

##
SRV_D=$SRV_HOME
PIDFILE=/var/run/$srv_n.pid
lockfile=/var/lock/$srv_n.lock
export GOPATH=$SRV_HOME
exec=$SRV_D/$exe_n
start() {
    [ -x $exec ] || exit 5

    umask 077

        echo -n "Starting $srv_n server: "
        daemonize -o /var/log/$srv_n/out.log -e /var/log/$srv_n/err.log -c $SRV_D -p $PIDFILE -u $usr_n -l $lockfile $exec conf/$exe_n.properties
        RETVAL=$?
    echo
        [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}
stop() {
        echo -n "Shutting down $srv_n server: "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
esac

exit $?
